version: 1
formatters:
  default:
    format: "%(asctime)s | %(levelname)s | %(name)s | %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
loggers:
  policy:
    level: INFO
    handlers: [console]
    propagate: false
root:
  level: INFO
  handlers: [console]
